#!/bin/sh

################################################################################
# Copyright (c) 2019 ModalAI, Inc. All rights reserved.
#
# Final setup for voxl_cam_manager.
################################################################################

set -e

# change default shell to bash
chsh -s /bin/bash
chmod 755 /usr/bin/voxl-image-streamer

# disable image compression with these two properties
# in the future we might turn compression on but for now it's safer off
setprop video.disable.ubwc 1
setprop persist.camera.preview.ubwc 0


echo ""
echo "done installing voxl_cam_manager"
echo ""